//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSW_BOOKS_DCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rel_BookCategory
    {
        public int Id { get; set; }
        public string ISBN { get; set; }
        public int IdCategory { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Category Category { get; set; }
    }
}
